"""Criação da tabela Aula

Revision ID: 88a1d8760428
Revises: 
Create Date: 2025-07-30 13:08:12.535176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88a1d8760428'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aula',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aluno', sa.String(length=100), nullable=False),
    sa.Column('professor', sa.String(length=100), nullable=False),
    sa.Column('data', sa.String(length=10), nullable=False),
    sa.Column('horario', sa.String(length=5), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aula')
    # ### end Alembic commands ###
